const productsData = [
  {
    id: 1,
    productName: "Laptop",
    productType: "Electronics",
    description: "High-performance laptop with advanced features.",
    price: 1200,
    dateOfIssue: "2022-03-15",
    quantity: 15,
    totalCost: 18000,
    toWhomIssued: "IT Department",
    quantityIssued: 5,
    availabilityInStock: 10,
  },
  {
    id: 2,
    productName: "Bookshelf",
    productType: "Furniture",
    description: "Sturdy bookshelf for organizing books and items.",
    price: 300,
    dateOfIssue: "2022-02-28",
    quantity: 8,
    totalCost: 2400,
    toWhomIssued: "Library",
    quantityIssued: 3,
    availabilityInStock: 5,
  },
  {
    id: 3,
    productName: "Smartphone",
    productType: "Electronics",
    description: "Latest smartphone with advanced camera and features.",
    price: 800,
    dateOfIssue: "2022-04-10",
    quantity: 20,
    totalCost: 16000,
    toWhomIssued: "Sales Department",
    quantityIssued: 8,
    availabilityInStock: 12,
  },
  {
    id: 4,
    productName: "Office Chair",
    productType: "Furniture",
    description: "Comfortable office chair with ergonomic design.",
    price: 150,
    dateOfIssue: "2022-03-05",
    quantity: 12,
    totalCost: 1800,
    toWhomIssued: ["HR Department", "islamyat", "Computer Science"],
    quantityIssued: 4,
    availabilityInStock: 8,
  },
  // Add more products as needed
];

export default productsData;
